### ISSUE TITLE
Setup Apollo Client

### ISSUE THREAD

**Issue by agentlewis** [Ecosify/COVID-Community-Health-App#13]
### Requirements
Setup Apollo client to use to interact with Amplify via graphql

### AC 
 - [ ] Rendering seed data on the device
 - [ ] Submitting a new high risk score to a location on the server

**Comment by agentlewis** [comment]
@simontegg hey bud I can't see any seed data on dev webview after merging https://github.com/Ecosify/COVID-Community-Health-App/pull/19. Lets keep this open until we can see the data coming through.

Happy to move the submitting AC to another ticket if we want to split up the scope - what do you think?

**Comment by simontegg** [comment]
yeah I have to manually run the seed script after tweaking to see it.

**Comment by agentlewis** [comment]
👍

**Comment by agentlewis** [comment]
@simontegg what does the process of seeding look like? is it something we can capture into a npm scirpt or should we just document it into an md file?
