### ISSUE TITLE
Determine if a user has completed onboarding

### ISSUE THREAD

**Issue by agentlewis** [Ecosify/COVID-Community-Health-App#24]
### Requirements

Given a user has downloaded the app
And they have created a user account (beta only)
When they open the app
Then show the user the onboarding screens

Given a user has downloaded the app
And they are already logged in (persisted session)
When they open the app
Then take them to the dashboard

### Proposed tech approach

@simontegg I was thinking the simplest way of doing this is to add a boolean to the users profile in dynamodb and note it as false until it is complete

Resulting in

Given a user has downloaded the app
And they have created a user account (beta only)
When they have completed the onboarding flow
Then send `onboardingComplete: true` to the server

thoughts? I am trying to see any downsides with the approach.

**Comment by agentlewis** [comment]
#26 adds a bool on the user object in amplify, we can use this to test whether we should skip onboarding.

**Comment by simontegg** [comment]
going to add a local user and track this state on them

**Comment by simontegg** [comment]
just gonna wait til `feat/auth` gets in
