### ISSUE TITLE
Use Switch Navigator to handle difference between Onboarding and Normal app navigation stack

### ISSUE THREAD

**Issue by agentlewis** [Ecosify/COVID-Community-Health-App#28]
### Requirements

Given a user has downloaded Safe2 for the first time
When the user opens the app
Than show the user the onboarding screens

Given a user has used Safe2 before (created an account)
And the credentials are stored in the safe enclave of the phone
When the user opens the app
Than show the user the dashboard

**Comment by agentlewis** [comment]
@iainkirkpatrick can I go over this with you?

Reading this article here: https://medium.com/the-react-native-log/building-an-authentication-flow-with-react-navigation-fb5de2203b5c

**Comment by iainkirkpatrick** [comment]
@agentlewis and I went over this on a call - SwitchNavigator is no longer part of v5 of React Navigation, the recommended approach is to just swap out the auth-protected screens from a stack with JS conditionals. Closing.
