### ISSUE TITLE
Form to assess symptoms saves locally

### ISSUE THREAD

**Issue by simontegg** [Ecosify/COVID-Community-Health-App#29]

**Comment by iainkirkpatrick** [comment]
Very happy to crunch this out - I'd use [Final Form](https://github.com/final-form/react-final-form) which is pretty quick to get going

**Comment by iainkirkpatrick** [comment]
OK Final Form doesn't look like it really supports React Native properly - looking briefly at Formik and maybe just rolling ourselves as we only have a single form

**Comment by iainkirkpatrick** [comment]
Pushed to `feature/assessment-form-stub` - the basics are there, the 'other symptoms' field isn't wired up to anything yet, probably just another piece of state we can send / save. @simontegg @agentlewis FYI
Just went standard inputs / checkboxes in the end, form libs either didn't play nice or were overkill

**Comment by simontegg** [comment]
I'm gonna comment out the "other symptoms" part. Edge use case. Maybe 2% of users will use this
