### ISSUE TITLE
Update/Get aws-exports.js after amplify configure succesful

### ISSUE THREAD

**Issue by agentlewis** [Ecosify/COVID-Community-Health-App#48]
Ok so along the way of reset some branches I lost the local amplify files. 

I thought no problem - determined I was still logged into the amplify console I just typed `amplify pull`.

It pulled down everything except the `aws-exportsjs` file.

Working through the cli I worked out I could type:

```SHELL
amplify env get --name develop --json > src\aws-exports.js
``` 

But then realised this doesn't create the file we need 👎 

So open question what is the command to recreate the aws-exports.js file from the cli?

Because at this point I can only see one brute force measure - logout of amplify cli and start again.

**Comment by agentlewis** [comment]
Well documented here: https://github.com/aws-amplify/amplify-cli/issues/186

If this is the same from machine to machine @simontegg could you add it as a lastpass note in the safe2 dev folder. Then I can just copy it down. Thanks

**Comment by agentlewis** [comment]
Ok the fix was to simply delete the repo, reclone it and re-init it.

**Comment by simontegg** [comment]
I haven't understood the problem. When pulling and environment that I don't have locally I've alsways used the command in the amplify console
