### ISSUE TITLE
Inital AppSync Schema

### ISSUE THREAD

**Issue by simontegg** [Ecosify/COVID-Community-Health-App#7]
The backend needs to track some data regarding locations while keeping users anonymous. 
Initial ideas for the schema follow. Please comment if you spot errors or something missing.

```
Location
 id: ID!
 address: String!
 lat: Float!
 lon: Float!
 country: String!
 region: String!
 postcode: Int!
 etc...
 score: Float | Int
```

Refer to the [MapBox Datatypes](https://docs.mapbox.com/api/search/#data-types) 

```
User:
 id: ID!

```

Cognito users are given an id and is linked to Personallly Identfiable Information (email, phone number). Presumably, the association between cognito id and User.id is only made on the user's device. 

And a record of when a user was at a Location. This is most similar to [Schema/Action](https://schema.org/Action)

```
Visit
 userId:  ID!
 locationId: ID!
 startTime: AWSDateTime
 endTime: AWSDateTime
```

Locations will have aggregated scores based on the user health scores that have visited the location

Request example
![image](https://user-images.githubusercontent.com/1574732/78105585-04802700-744e-11ea-8ebe-46af0fc1a0fd.png)

**Comment by simontegg** [comment]
NB: making minor adjustments to an amplify schema can sometimes mean destroying and recreating the schema, which is timeconsuming. Good to get things hashed out in comments.

**Comment by agentlewis** [comment]
@simontegg if this does come to pass in prod what is the process for preserving data through the descroy/recreate? or does the schema not have hard constraints on dynamoDB?

**Comment by simontegg** [comment]
@agentlewis 
Its doable in production but needs careful planning, similar to relational databases. 
1. add a new field or an entirely new replacement table. 
2.  deploy a lambda that migrates data over to new schema and keeps old and new schemas in sync. You're still using the old API but you now have a live copy table in the new setup. The streaming capability of dynamodb makes this a lot easier than a SQL db.
3. test new setup for accuracy and consistency. 
4. deploy a new API that interfaces with new schema and client app. With a web app you can alert users to refresh the client. More complicated with a distributed mobile app, though with the over-the-cloud JS/CSS updates its possible it could work similarly.

**Comment by simontegg** [comment]
subtasks: 
- [] create schema with types, @model, @key, @connection, @auth directives
- [] script to seed data into tables
- [] setup apollo client query and display data, 
- [] push and seek feedback

**Comment by simontegg** [comment]
@agentlewis @iainkirkpatrick Its not clear that we should use Apollo Client. 
Amplify has a thing called [DataStore](https://aws-amplify.github.io/docs/js/datastore#datastore) that would seem to do a better job with offline storage and update

**Comment by iainkirkpatrick** [comment]
that looks interesting @simontegg - didn't know about it!

**Comment by agentlewis** [comment]
@simontegg yes your absolutely right.i was going through the amplify features looking for documentation on the directives.

I looked at datastore for a moment and thought it wouldn't work for us as we have to store data on the local device. However thinking about it now that doesn't make sense. We can absolutely use it for connecting to ampify for the server data. 

I guess we would then need to have a second local data service. though we would have needed that with appollo as well 🤪

thanks for pointing this out! right time to catch it

**Comment by simontegg** [comment]
Probably have to go through API creation options again to get Datastore sync to work
https://github.com/aws-amplify/amplify-ios/issues/340

and this is not an encoraging issue

**Comment by agentlewis** [comment]
@simontegg One more thing we need to consider for datastore vs apollo is our users privacy.

Jamison has cleary directed us to not use a pub/sub model for fetching data as this would require knowing what device would be subscribed to the database.

Can you clarify what your understanding of datastore is in this regard?
